FROM scratch

COPY ./ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY ./bin/server /server

USER 999

EXPOSE 9999


ENTRYPOINT ["/server"]
# --grpc_endpoint value to be set by the environment
CMD ["--cnss_endpoint=:55678","--zpgz_endpoint=:9999"]
